### PR TITLE
bugfix: fixed next page id calculation

### LINKED ISSUE #194: [Bug]
# Description

When importing a lot of users on a non-existing graph the page calculation always returns 0 since it does not count the updated pages. Which in result only exports 1 page instead of all of them.

# Acceptence Criterea
- Use updated pages in next_page_id calculations

### PR DESCRIPTION
**Pull request by aramikm**
# Goal
The goal of this PR is fix the bug which exports only the last page instead of all of them when more than 1 page is created via adding connections.

Closes #194 

# Checklist
- [X] updated versions
- [X] Tests added

### CODE REVIEW

File: core/src/graph/graph.rs [hunk 1]
```diff
@@ -890,7 +899,35 @@ mod test {
 			))),
 		};
 
-		assert_eq!(graph.get_next_available_page_id(), Some(8));
+		assert_eq!(graph.get_next_available_page_id(&BTreeMap::default()), Some(8));
+	}
+
+	#[test]
+	fn get_next_available_page_should_include_updated_pages() {
```
Comment (JoeCap08055) [inline core/src/graph/graph.rs:906]: 💯

**Review by JoeCap08055 — APPROVED** [review]

File: core/src/api/api.rs [hunk 2]
```diff
@@ -733,7 +733,7 @@ mod test {
 	}
 
 	#[test]
-	#[timeout(3000)]
+	#[timeout(30000)]
```
Comment (JoeCap08055) [inline core/src/api/api.rs]: Timed out in CI
```suggestion
	#[timeout(60000)]
```

**Review by saraswatpuneet — APPROVED** [review]
