### PR TITLE
Better errors

### LINKED ISSUE #28: [GraphSDK] better errors
Currently errors are lacking deep context, we would like to add stack trace or more verbose "useable" errors and.
- More FFI friendly errors

### PR DESCRIPTION
**Pull request by saraswatpuneet**
# Goal
The goal of this PR is to define custom graph sdk type errors and modify underlying traits and implementation to return custom type instead

Closes #28 

# Discussion

# Checklist
- [ ] Tests added

### CODE REVIEW

File: config/src/errors.rs [hunk 1]
```diff
@@ -0,0 +1,180 @@
+//! Errors for graph-sdk crate
```
Comment (saraswatpuneet) [inline config/src/errors.rs:1]: Various errors returned from sdk

File: config/src/errors.rs [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+//!
+
+use thiserror::Error;
+
+pub type DsnpGraphResult<T> = std::result::Result<T, DsnpGraphError>;
```
Comment (saraswatpuneet) [inline config/src/errors.rs:6]: graph sdk `Result` type

File: config/src/errors.rs [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+	// Invalid Page ID
+	#[error("Invalid Page ID: {0}")]
+	InvalidPageId(String),
+
+	// Page error
+	#[error("Page error: {0}")]
+	PageError(String),
+
+	// "Connection from {} to {} does not exists to be disconnected!"
+	#[error("Connection from {0} to {1} does not exists!")]
```
Comment (JoeCap08055) [inline config/src/errors.rs:67]: s/exists/exist/

File: config/src/errors.rs [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+}
+
+impl From<apache_avro::Error> for DsnpGraphError {
+	fn from(error: apache_avro::Error) -> Self {
+		// Convert the underlying error to DsnpGraphError variant
+		// based on your error handling logic
+		// For example:
+		DsnpGraphError::AvroError(error.to_string())
+	}
+}
```
Comment (JoeCap08055) [inline config/src/errors.rs:180]: Why not instead define `DsnpGraphError::AvroError` as:
```
#[error(transparent)]
AvroError(#[from] apache_avro::Error)
```

...will auto-generate a `From<apache_avro::Error>` implementation

File: config/src/errors.rs [hunk 5]
```diff
@@ -0,0 +1,180 @@
+//! Errors for graph-sdk crate
+//!
+
+use thiserror::Error;
+
+pub type DsnpGraphResult<T> = std::result::Result<T, DsnpGraphError>;
+
+#[derive(Debug, Error)]
+pub enum DsnpGraphError {
```
Comment (JoeCap08055) [inline config/src/errors.rs:9]: q: why are all values `String` instead of, for instance, `DsnpUserId` or other types? Is it specifically for C-compatibility? It seems like the `thiserror` crate gives us a lot of flexibility to keep the underlying data types while still producing a `Display` trait with a formatted string.

**Review by aramikm — COMMENTED** [review]
Great work! Added some suggestions and also I think we would need to modify the tests to check against those specific errors instead of currently only checking `is_err`

File: config/src/errors.rs (hunk 5 above)
Comment (JoeCap08055) [inline config/src/errors.rs:9]: Do we want to `#[repr(C, u8)]` this? Or otherwise we'll need to wrap it in something for the FFI.

File: config/src/errors.rs (hunk 4 above)
Comment (saraswatpuneet) [reply config/src/errors.rs:180]: Yep i like that

File: config/src/errors.rs [hunk 6]
```diff
@@ -0,0 +1,180 @@
...
+	// Errors related to Avro
+	#[error("Avro error: {0}")]
+	AvroError(String),
```
[the remark this answers is not in the document]
Comment (saraswatpuneet) [reply config/src/errors.rs]: I sorted them but since they are not unit variants and contains tuples we cannot achieve pinning the values like =1 etc.
One way to achieve this especially for ffi is assign them some code via function call, 

Let me know how you feel about it

File: Makefile [hunk 7]
```diff
@@ -15,9 +15,10 @@ clippy:
 	@echo "Running Cargo clippy..."
 	@cargo clippy --all --all-features --all-targets -- -D warnings
 
-.PHONY: fmt
-fmt:
+.PHONY: format
+format:
 	@echo "Running Cargo fmt..."
+	@cargo fmt
```
[the remark this answers is not in the document]
Comment (saraswatpuneet) [reply Makefile]: I meant to separate the formatting and checking, but yes in CI we should only check than format

File: core/src/dsnp/schema.rs [hunk 8]
```diff
@@ -87,10 +88,11 @@ mod test {
 		let deserialized = SchemaHandler::read_public_key(&serialized);
 
 		assert!(deserialized.is_err());
-		assert!(matches!(
-			deserialized.unwrap_err().downcast_ref::<AvroError>(),
-			Some(AvroError::ConvertI64ToUsize(_, _))
-		))
+		let returned_err = deserialized.unwrap_err();
+		match returned_err {
```
[the remark this answers is not in the document]
Comment (saraswatpuneet) [reply core/src/dsnp/schema.rs]: Yep, that suggest from Joe help to match exact error

File: core/src/dsnp/api_types.rs [hunk 9]
```diff
@@ -1,8 +1,14 @@
 use crate::dsnp::{dsnp_configs::KeyPairType, dsnp_types::DsnpUserId};
-pub use dsnp_graph_config::{ConnectionType, PrivacyType};
+pub use dsnp_graph_config::{ConnectionType, PageId as PageIdType, PrivacyType};
 use dsnp_graph_config::{GraphKeyType, SchemaId};
 use std::{cmp::Ordering, fmt::Debug};
 
+/// Graph page id
+pub type PageId = PageIdType;
+
```
Comment (JoeCap08055) [inline core/src/dsnp/api_types.rs:8]: I think if you just do `pub use dsnp_graph_config::PageId` it will re-export; you don't need to redefine the `PageId` type again.

File: core/src/dsnp/dsnp_types.rs [hunk 10]
```diff
@@ -1,4 +1,5 @@
 use anyhow::Result;
+use dsnp_graph_config::DsnpUserId as DsnpUserIdType;
```
Comment (JoeCap08055) [inline core/src/dsnp/dsnp_types.rs:2]: Same as above comment on `PageId`

**Review by aramikm — APPROVED** [review]
Looks great!

File: config/src/errors.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (JoeCap08055) [reply config/src/errors.rs]: Not necessarily true; for instance, given the following enum:
```
#[repr(C)]
pub enum MyError {
   Error1 = 1,
   Error2(u8) = 2,
   Error3(String) = 3,
   Error4 { uid: u8, name: String } = 4,
}
```

cbindgen does generate integer-valued C-style enums. Here is the cbindgen output for that enum:
```
typedef struct String String;

typedef enum {
  Error1 = 1,
  Error2 = 2,
  Error3 = 3,
  Error4 = 4,
} MyError_Tag;

typedef struct {
  uint8_t uid;
  String name;
} Error4_Body;

typedef struct {
  MyError_Tag tag;
  union {
    struct {
      uint8_t error2;
    };
    struct {
      String error3;
    };
    Error4_Body error4;
  };
} MyError;
```

See here for more explanation:
https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#:~:text=Explicit%20repr%20annotation%20with%20C%20compatibility

It may not do any good in Rust, but the error struct exposed to the C API would expose the integer value of the enum.
